### PR TITLE
Nuclei segmentation using cv2

### PR DESCRIPTION
**Pull request by leonardosepulveda**
I incorporated multiple classes to segment.py. Still in development.

### CODE REVIEW

**Comment by emanuega** [comment]
I might suggest putting some of the functional code in the merlin/util/watershed.py module. This will make it easier to test each function without the need to run the analysis task. Additionally, this would allow you to write unit tests that will help ensure functionality is conserved in all future versions of merlin. See for example the tests in the test directory.

**Comment by leonardosepulveda** [comment]
Thanks for the comment. I will move some of the code to the watershed folder.

**Comment by leonardosepulveda** [comment]
Several of the tests in ci/circleci: build that crash are related to parts of merlin I have not modified. I am getting error messages from modification in another branch, or there may be other reason for them? Any ideas?

**Comment by emanuega** [comment]
Yes, the data portal errors are because the AWS test bucket on the zhuang account has been removed and the other error is a dependency version incompatibility. I added a couple commits to the master branch to fix these problems. If you cherrypick these into your branch the problem should be solved.

**Pull request closed without merging**
